version: '3.4'

services:
  backend:
    image: corpool-backend
    depends_on:
     - mongo-primary
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SUB_ENV=Docker
      - ASPNETCORE_URLS=http://+:80
      - Mongo__Host=mongo-primary
      - Mongo__Port=27017
      - Mongo__Username=root
      - Mongo__Password=root
      - Mongo__ReplicaSetName=replicaset
  
  frontend:
    image: corpool-frontend
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile

  revproxy:
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "${APP_LOCAL_PORT}:80"
    volumes:
      - "./docker/reverseproxy:/etc/nginx/templates/"
    environment:
      - BACKEND_DOCKER_ADDRESS=backend:80
      - FRONTEND_DOCKER_ADDRESS=frontend:80
      - BACKEND_LOCAL_ADDRESS=${HOST_IP}:${BACKEND_LOCAL_PORT}
      - FRONTEND_LOCAL_ADDRESS=${HOST_IP}:${FRONTEND_LOCAL_PORT}

  # MongoDB replication set
  mongo-primary:
    image: 'bitnami/mongodb:latest'
    restart: always
    hostname: mongo-primary
    ports:
      - "${MONGO_LOCAL_PORT}:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=corpoolreplica
    volumes:
      - mongo-data:/bitnami/mongodb
    
  mongo-secondary-1: # we can't make it scalable in develop since name resolving is not deterministic
    image: 'bitnami/mongodb:latest'
    restart: always
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary-1
      - MONGODB_REPLICA_SET_KEY=corpoolreplica
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root

  mongo-secondary-2: # we can't make it scalable in develop since name resolving is not deterministic
    image: 'bitnami/mongodb:latest'
    restart: always
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary-2
      - MONGODB_REPLICA_SET_KEY=corpoolreplica
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root

volumes:
  mongo-data: