version: '3.4'

services:
  backend:
    image: corpool-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SUB_ENV=Docker
      - ASPNETCORE_URLS=http://+:80
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO__USERNAME=root
      - MONGO__PASSWORD=root
    ports:
      - "33080:80"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro # this is a windows trick for getting the ssl to work
  
  frontend:
    image: corpool-frontend
    depends_on:
      - backend
    ports:
      - "32080:80"
    environment:
      - BACKEND_SERVER=backend
      - BACKEND_PORT=80
    build:
      context: frontend
      dockerfile: Dockerfile


  # mongodb replication set
  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  
  mongo1:
    hostname: mongo1
    image: mongo
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volumes/mongodb/data1/db:/data/db 
      - ./volumes/mongodb/data1/configdb:/data/configdb

  mongo2:
    hostname: mongo2
    image: mongo
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volumes/mongodb/data2/db:/data/db
      - ./volumes/mongodb/data2/configdb:/data/configdb

  mongo3:
    hostname: mongo3
    image: mongo
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volumes/mongodb/data3/db:/data/db
      - ./volumes/mongodb/data3/configdb:/data/configdb