apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "worker.fullname" . }}
  labels:
    app: {{ template "worker.name" . }}
    chart: {{ template "worker.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "worker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "worker.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            exec:
              command:
                - cat
                - {{ .Values.probes.path }}
          readinessProbe:
            exec:
              command:
                - cat
                - {{ .Values.probes.path }}
          {{- end }}
          env:
            # Probes ENV
            {{- if .Values.probes.enabled }}
            - name: HealthCheck__Enabled
              value: "true"
            - name: HealthCheck__FilePath
              value: {{ .Values.probes.path }}
            {{- end }}
            # Secrets ENV
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}__{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "worker.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            # Normal ENV
            {{- with .Values.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
